- name: Demo on taking the inputs from prompt and printing it
  hosts: frontend
  #connection: local
  vars_prompt:
    - name: username
      prompt: Please enter your username
      private: false
    
    - name: password
      prompt: Please enter your password
      private: false

  tasks:
   - name: Print the values
     debug:
      msg: "Username is {{username}} Password is {{password}} "


#Please enter your username: Ganesh
#Please enter your password: Ganesh

#PLAY [Demo on taking the inputs from prompt and printing it] ****************************************************************************************************************************

#TASK [Gathering Facts] ******************************************************************************************************************************************************************
#ok: [172.31.43.222]

#TASK [Print the values] *****************************************************************************************************************************************************************
#ok: [172.31.43.222] => {
#    "msg": "Username is Ganesh Password is Ganesh "
