- name: Demo on Variable Files
  hosts: localhost
  connection: local
  vars_files:
  - varsfile.yaml
  tasks:
  - name: print Variables
    debug:
     msg: " Hi, I am {{NAME}}, I'm {{AGE}} years old from {{PLACE}}"

#TASK [print Variables] ******************************************************************************************************************************************************************
#ok: [localhost] => {
#    "msg": " Hi, I am Ganesh, I'm 25 years old from Miryalaguda"
