- name: Demo on Dtatypes
  hosts: local
  connection: local
  vars:
    course: "DevSecOps with AI/ML" # String
    duration_in_hrs: 150 # Integer
    is_live: true  #Boolean
    topics: #LIST
    - linux
    - git
    - shell
    - ansible
    more_details:
      months: 5
      trainer: siva
    
  tasks:
   - name: Print the Details of the course
     debug:
        msg : |
          name: {{course}}
          duration: {{duration_in_hrs}}
          is_it_Live: {{is_live}}
          topics: {{topics}}
          more_details: {{more_details}}