- name: check  number of live sessions
  hosts: local
  connection: local
  vars:
    live_sessions: 6
  tasks:
  - name: is ansible sessions count more than 5 ?
    debug:
      msg: " Yes, more than 5 sessions "
    when: live_sessions > 5



#[ ec2-user@ip-172-31-39-29 ~/Ansible ]$ ansible-playbook -i inventory.ini 40-conditions.yaml
#
#PLAY [check  number of live sessions] ***************************************************************************************************************************************************
#
#TASK [Gathering Facts] ******************************************************************************************************************************************************************
#ok: [localhost]
#
#TASK [is ansible sessions count more than 5 ?] ******************************************************************************************************************************************
#k: [localhost] => {
#    "msg": " Yes, more than 5 sessions "

