- name: Even or Odd
  hosts: local
  connection: local
  vars:
    given_number: 7
  tasks:
  - name: Is even 
    debug:
      msg: " {{given number}} is even"
    when: given_number % 2 == 0

  tasks:
  - name: Is odd
    debug:
      msg: " {{given number}} is odd"
    when: given_number % 2 != 0