- name: Conditions using Ansible facts
  hosts: frontend
  #connection: local
  tasks:
  - name: Print if OS release is RedHat
    debug:
      msg: " This is Redhat distro, package is dnf ... "
    when: ansible_facts.os_family == "RedHat"

  - name: Print if OS release is Ubuntu
    debug:
      msg: " This is Ubuntu distro, package is apt "
    when: ansible_facts.os_family == "Ubuntu"

  - name: Print if OS release is Debian
    debug:
      msg: " This is Debian distro, package is apt-get "
    when: ansible_facts.os_family == "Debian"