- name: Conditions using Ansible facts
  hosts: frontend
  #connection: local
  tasks:
  - name: Print if OS release is RedHat
    debug:
      msg: " This is Redhat distro, package is dnf ... "
    when: ansible_facts.os_family == "RedHat"

  - name: Print if OS release is Ubuntu
    debug:
      msg: " This is Ubuntu distro, package is apt "
    when: ansible_facts.os_family == "Ubuntu"

  - name: Print if OS release is Debian
    debug:
      msg: " This is Debian distro, package is apt-get "
    when: ansible_facts.os_family == "Debian"


#[ ec2-user@ip-172-31-39-29 ~/Ansible ]$ ansible-playbook -i inventory.ini 42-ans-facts-conditions.yaml
#
#PLAY [Conditions using Ansible facts] ***************************************************************************************************************************************************
#
#TASK [Gathering Facts] ******************************************************************************************************************************************************************
#ok: [172.31.46.249]
#
#TASK [Print if OS release is RedHat] ****************************************************************************************************************************************************
#ok: [172.31.46.249] => {
#    "msg": " This is Redhat distro, package is dnf ... "
#}
#
#TASK [Print if OS release is Ubuntu] ****************************************************************************************************************************************************
#skipping: [172.31.46.249]
#
#TASK [Print if OS release is Debian] ****************************************************************************************************************************************************
#skipping: [172.31.46.249]
