[local]
localhost

[frontend]
172.31.43.222

[catalogue]

[user]

[cart]

[shipping]

[payment]

[mongodb]

[redis]

[mysql]

[rabbitmq]

[roboshop:children]
frontend
catalogue
user
cart
shipping
payment
mongodb
redis
mysql
rabbitmq

[local:vars]
NAME: Ganesh
AGE: 25
PLACE: Miryalaguda
MOBILE: 7730835238

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321


