- name: Demo on Variables in localhost
  hosts: localhost
  connection: local
  vars:
    Name: "Ganesh"
    Age: 25
    Place: "Miryalaguda"
  tasks:
  - debug: 
     msg: " Hi, I am {{Name}}, I'm {{Age}} years old from {{place}} "