- name: Demo on Variables in Task Object
  hosts: localhost
  connection: local
  vars:
    Name: "Ganesh"
    Age: 25
    Place: "Miryalaguda"
  tasks:
  - name: Task level Variables
    vars:
      Name: Sai
    debug: 
     msg: " Hi, I am {{Name}}, I'm {{Age}} years old from {{Place}} "