- name: Demo on prompt [ reading values from prompt ]
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: Please enter your username
    private: false

  - name: password
    prompt: Please enter your password
    private: true

  tasks:
  - name: print
    debug:
     msg: " {{username}} {{password}} "