- name: Demo on taking the inputs from prompt and printing it
  hosts: localhost
  connection: local
  vars_prompt:
    - name: username
      prompt: Please enter your username
      private: false
    
    - name: password
      prompt: Please enter your password
      private: false

  tasks:
   - name: Print the values
     debug:
      msg: "Username is {{username}} Password is {{password}} "