- name: Demo on variables from inventory Files
  hosts: local
  connection: local
  tasks:
  - name: Demo on variables from inventory Files
    debug:
      msg: " Hi, I am {{NAME}}, I'm {{AGE}} years old from {{PLACE}} "